name: interconnectionplayerpaper
version: '${version}'
main: com.foxapplication.mc.interconnectionplayer.paper.InterconnectionPlayerPaper
api-version: '1.20'
load: STARTUP
depend: [ interconnectionpaper ]
authors: [ KenRouKoro ]
